fr_to_en = {
    "chat": "cat",
    "chien": "dog",
    "oiseau": "bird",
    "cheval": "horse",
    "poisson": "fish",
    "souris": "mouse",
    "vache": "cow",
    "mouton": "sheep",
    "lapin": "rabbit",
    "serpent": "snake",
    "grenouille": "frog",
    "cochon": "pig",
    "tigre": "tiger",
    "lion": "lion",
    "éléphant": "elephant",
    "singe": "monkey",
    "requin": "shark",
    "baleine": "whale",
    "araignée": "spider",
    "poule": "hen",
    "canard": "duck",
    "papillon": "butterfly",
    "abeille": "bee",
    "fourmi": "ant",
    "coccinelle": "ladybug",
    "loup": "wolf",
    "renard": "fox",
    "ours": "bear",
    "hibou": "owl",
    "aigle": "eagle",
    "pigeon": "pigeon",
    "perroquet": "parrot",
    "crabe": "crab",
    "escargot": "snail",
    "dauphin": "dolphin",
    "tortue": "turtle",
    "rat": "rat",
    "crocodile": "crocodile",
    "hippopotame": "hippopotamus",
    "kangourou": "kangaroo",
    "panda": "panda",
    "zèbre": "zebra",
    "girafe": "giraffe",
    "chameau": "camel",
    "autruche": "ostrich",
    "pingouin": "penguin",
    "loutre": "otter",
    "iguane": "iguana",
    "buffle": "buffalo",
    "chèvre": "goat",
    "paon": "peacock",
    "pieuvre": "octopus",
    "requin-marteau": "hammerhead shark",
    "anaconda": "anaconda",
    "porc-épic": "porcupine",
    "chinchilla": "chinchilla",
    "puma": "puma",
    "panthère": "panther",
    "cerf": "deer",
    "bison": "bison",
    "hirondelle": "swallow",
    "corbeau": "crow",
    "faucon": "falcon",
    "mouette": "seagull",
    "poule d'eau": "moorhen",
    "flamant rose": "flamingo",
    "dindon": "turkey",
    "pie": "magpie",
    "buse": "buzzard",
    "chevreuil": "roe deer",
    "sanglier": "wild boar",
    "lièvre": "hare",
    "hermine": "ermine",
    "blaireau": "badger",
    "chouette": "barn owl",
    "écureuil": "squirrel",
    "castor": "beaver",
    "coyote": "coyote",
    "lynx": "lynx",
    "lémurien": "lemur",
    "furet": "ferret",
    "caribou": "caribou",
    "phoque": "seal",
    "manchot": "penguin",
    "raton laveur": "raccoon",
    "morse": "walrus",
    "koala": "koala",
    "tapir": "tapir",
    "wombat": "wombat",
    "wallaby": "wallaby",
    "caïman": "caiman",
    "gavial": "gharial",
    "mangouste": "mongoose",
    "babouin": "baboon",
    "lemurien": "lemur",
    "dingo": "dingo"
}


while True:
    word_fr = input("Entrez un nom d'animal en français (tapez 'exit' pour quitter) : ")
    
    if word_fr.lower() == 'exit':
        print("Programme terminé.")
        break

    if word_fr in fr_to_en:
        print(f"Traduction : {fr_to_en[word_fr]}")
    else:
        print("Traduction non disponible")